require:
  - rubocop-performance
inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "vendor/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "bin/**/*"
    - "spec/**/*"
    - "db/migrate/**/*"
    - "db/schema.rb"
