version: '3.7'

volumes:
  db-data:
  cache-data:

services:
  db:
    image: postgres:11
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  cache:
    image: redis:4.0
    volumes:
      - cache-data:/data
    ports:
      - '6379:6379'
