version: '3.7'

x-app: &app
  build: .
  environment: &app-environments
    TZ: Asia/Tokyo
    EDITOR: vi
    APP_PATH: /app
    HISTFILE: /app/log/.bash_history
    RAILS_ENV: development
    POSTGRES_HOST: db
    POSTGRES_USERAME: postgres
    POSTGRES_PASSWORD:
    REDIS_URL: redis://cache:6379
    SMTP_USERNAME:
    SMTP_PASSWORD:
    SMTP_ADDRESS: smtp
    SMTP_PORT: 1025
    NODE_ENV: development
    WEBPACKER_DEV_SERVER_HOST: webpack-dev-server
    WEBPACKER_DEV_SERVER_PORT: 3035
    WEBPACKER_DEV_SERVER_PUBLIC: localhost:3035
  volumes:
    - .:/app:cached
    - /app/tmp/cache
    - /app/tmp/pids
    - /app/.git
    - bundler-data:/usr/local/bundle
    - yarn-data:/app/node_modules
    - packs-data:/app/public/packs

volumes:
  bundler-data:
  yarn-data:
  db-data:
  cache-data:
  packs-data:

services:
  db:
    image: postgres:11
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  cache:
    image: redis:4.0
    volumes:
      - cache-data:/data
    ports:
      - '6379:6379'

  rails:
    <<: *app
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true

#  resque:
#    <<: *defaults
#    command: bundle exec rails resque:work
#    tty: true
#    stdin_open: true

  webpack-dev-server:
    <<: *app
    environment:
      <<: *app-environments
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    command: bin/webpack-dev-server
    ports:
      - '3035:3035'

  runner:
    <<: *app
    command: /bin/bash
    stdin_open: true
    tty: true
