version: 2.1
executors:
  app:
    working_directory: ~/blog
    shell: /bin/bash --login
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: ""
          REDIS_URL: redis://localhost:6379
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          YARN_CACHE_FOLDER: ~/.cache/yarn
          DISABLE_SPRING: true
          COVERAGE: true
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: blog_test
          POSTGRES_PASSWORD: ""

commands:
  setup_bundler:
    description: Setup bundler
    steps:
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - rails-bundle-{{ checksum "Gemfile.lock" }}
            - rails-bundle-
      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment
      - save_cache:
          key: rails-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  setup_yarn:
    description: Setup Yarn
    steps:
      - restore_cache:
          keys:
            - rails-yarn-{{ checksum "yarn.lock" }}
            - rails-yarn-
      - run:
          name: Yarn Install
          command: yarn install --check-files --cache-folder ~/.cache/yarn
      - run:
          name: Check Yarn Integrity
          command: yarn check --integrity
      - save_cache:
          key: rails-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  setup_db:
    description: Setup DB
    steps:
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:create db:schema:load --trace

  audit_gem:
    description: Audit RubyGems
    steps:
      - run:
          name: Audit RubyGems
          command: bundle exec bundle audit check --update

  audit_npm:
    description: Audit npm
    steps:
      - run:
          name: Audit npm
          command: yarn audit-ci -m

  rubocop:
    description: Rubocop
    steps:
      - run:
          name: Run Rubocop
          command: bundle exec rubocop

  eslint:
    description: ESLint
    steps:
      - run:
          name: Run ESLint
          command: yarn eslint app/javascript

  compiling_assets:
    description: Compiling Assets
    steps:
      - restore_cache:
          keys:
            - asset-cache-{{ arch }}-{{ .Branch }}
            - asset-cache-
      - run:
          name: Compiling Assets
          command: bundle exec rails assets:precompile
      - save_cache:
          key: asset-cache-{{ arch }}-{{ .Branch }}-{{ epoch }}
          paths:
            - public/assets
            - public/packs
            - tmp/cache/assets/sprockets

  rspec:
    description: Run Specs
    steps:
      - run:
          name: Run Specs
          command: |
            echo "--format progress --format RspecJunitFormatter --out tmp/test-results/rspec/rspec.xml" > .rspec
            bundle exec rspec --format progress --format RspecJunitFormatter --out tmp/test-results/rspec/rspec.xml

  save_test_results:
    description: Save test results
    steps:
      - store_test_results:
          path: tmp/test-results

  save_artifacts:
    description: Save artifacts
    steps:
      - store_artifacts:
          path: tmp/screenshots
          destination: screenshots
      - store_artifacts:
          path: coverage
          destination: coverage

jobs:
  audit_gem:
    executor: app
    steps:
      - checkout
      - setup_bundler
      - audit_gem

  audit_npm:
    executor: app
    steps:
      - checkout
      - setup_yarn
      - audit_npm

  lint_ruby:
    executor: app
    steps:
      - checkout
      - setup_bundler
      - rubocop

  lint_javascript:
    executor: app
    steps:
      - checkout
      - setup_yarn
      - eslint

  spec:
    executor: app
    steps:
      - checkout
      - setup_bundler
      - setup_yarn
      - setup_db
      - compiling_assets
      - rspec
      - save_test_results
      - save_artifacts

workflows:
  version: 2
  commit:
    jobs:
      - lint_ruby
      - lint_javascript
      - spec
  daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - audit_gem
      - audit_npm
      - spec
