host: <%= ENV.fetch("WWW_HOST") { "" } %>
basic_authentication:
  user: <%= ENV.fetch("BASIC_AUTHENTICATION_USER") { "" } %>
  password: <%= ENV.fetch("BASIC_AUTHENTICATION_PASSWORD") { "" } %>
  allow_user_agent: <%= ENV.fetch("BASIC_AUTHENTICATION_ALLOW_USER_AGENT") { "" } %>
