cache_store:
  redis:
    namespace: cache
    url: <%= ENV.fetch("REDIS_URL") %>
carrierwave:
  storage: aws
  aws_bucket: <%= ENV.fetch("UPLOADS_AWS_BUCKET") %>
  aws_acl: public-read
  asset_host: <%= ENV.fetch("UPLOADS_ASSET_HOST") %>
  aws_attributes:
    expires: <%= 1.week.from_now.httpdate %>
    cache_control: max-age=<%= 1.week.to_i %>
  aws_credentials:
    region: <%= ENV.fetch("UPLOADS_AWS_REGION") %>
    aws_access_key_id: <%= ENV.fetch("AWS_ACCESS_KEY_ID") %>
    aws_secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY") %>
